FROM node:22-alpine

WORKDIR /app

# Instala dependencias de sistema si tu proyecto las usa
# RUN apk add ...

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev", "--", "--host"]